[package]
name = "love-letter"
version = "0.1.0"
authors = ["scl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
rand = "0.7"
